<?php
/**
 * ResourceProcessorApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Asset Processor API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\AssetProcessor\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Aurigma\AssetProcessor\ApiException;
use Aurigma\AssetProcessor\Configuration;
use Aurigma\AssetProcessor\HeaderSelector;
use Aurigma\AssetProcessor\ObjectSerializer;

/**
 * ResourceProcessorApi Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ResourceProcessorApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'resourceProcessorImportResource' => [
            'multipart/form-data',
        ],
        'resourceProcessorImportResourceFromUrl' => [
            'application/json',
        ],
        'resourceProcessorUpdate' => [
            'multipart/form-data',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation resourceProcessorImportResource
     *
     * Imports a resource from the source file and saves it to the storage.
     *
     * @param  \SplFileObject $source_file Resource source file. (required)
     * @param  int $tenant_id Tenant ID. (optional)
     * @param  string $name Resource name. (optional)
     * @param  string $namespace Resource namespace. (optional)
     * @param  string $source_id Resource source identifier. (optional)
     * @param  array<string,mixed> $custom_fields Resource custom fields. (optional)
     * @param  string $type Resource type. (optional)
     * @param  string $format Resource format. (optional)
     * @param  bool $anonymous_access Indicates if a resource should be available by link without authorization. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resourceProcessorImportResource'] to see the possible values for this operation
     *
     * @throws \Aurigma\AssetProcessor\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Aurigma\AssetProcessor\Model\ResourceDto|\Aurigma\AssetProcessor\Model\ProblemDetails|\Aurigma\AssetProcessor\Model\ResourceImportConflictDto
     */
    public function resourceProcessorImportResource($source_file, $tenant_id = null, $name = null, $namespace = null, $source_id = null, $custom_fields = null, $type = null, $format = null, $anonymous_access = null, string $contentType = self::contentTypes['resourceProcessorImportResource'][0])
    {
        list($response) = $this->resourceProcessorImportResourceWithHttpInfo($source_file, $tenant_id, $name, $namespace, $source_id, $custom_fields, $type, $format, $anonymous_access, $contentType);
        return $response;
    }

    /**
     * Operation resourceProcessorImportResourceWithHttpInfo
     *
     * Imports a resource from the source file and saves it to the storage.
     *
     * @param  \SplFileObject $source_file Resource source file. (required)
     * @param  int $tenant_id Tenant ID. (optional)
     * @param  string $name Resource name. (optional)
     * @param  string $namespace Resource namespace. (optional)
     * @param  string $source_id Resource source identifier. (optional)
     * @param  array<string,mixed> $custom_fields Resource custom fields. (optional)
     * @param  string $type Resource type. (optional)
     * @param  string $format Resource format. (optional)
     * @param  bool $anonymous_access Indicates if a resource should be available by link without authorization. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resourceProcessorImportResource'] to see the possible values for this operation
     *
     * @throws \Aurigma\AssetProcessor\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Aurigma\AssetProcessor\Model\ResourceDto|\Aurigma\AssetProcessor\Model\ProblemDetails|\Aurigma\AssetProcessor\Model\ResourceImportConflictDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function resourceProcessorImportResourceWithHttpInfo($source_file, $tenant_id = null, $name = null, $namespace = null, $source_id = null, $custom_fields = null, $type = null, $format = null, $anonymous_access = null, string $contentType = self::contentTypes['resourceProcessorImportResource'][0])
    {
        $request = $this->resourceProcessorImportResourceRequest($source_file, $tenant_id, $name, $namespace, $source_id, $custom_fields, $type, $format, $anonymous_access, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 201:
                    if ('\Aurigma\AssetProcessor\Model\ResourceDto' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Aurigma\AssetProcessor\Model\ResourceDto' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Aurigma\AssetProcessor\Model\ResourceDto', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Aurigma\AssetProcessor\Model\ProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Aurigma\AssetProcessor\Model\ProblemDetails' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Aurigma\AssetProcessor\Model\ProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 409:
                    if ('\Aurigma\AssetProcessor\Model\ResourceImportConflictDto' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Aurigma\AssetProcessor\Model\ResourceImportConflictDto' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Aurigma\AssetProcessor\Model\ResourceImportConflictDto', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Aurigma\AssetProcessor\Model\ResourceDto';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Aurigma\AssetProcessor\Model\ResourceDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Aurigma\AssetProcessor\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Aurigma\AssetProcessor\Model\ResourceImportConflictDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation resourceProcessorImportResourceAsync
     *
     * Imports a resource from the source file and saves it to the storage.
     *
     * @param  \SplFileObject $source_file Resource source file. (required)
     * @param  int $tenant_id Tenant ID. (optional)
     * @param  string $name Resource name. (optional)
     * @param  string $namespace Resource namespace. (optional)
     * @param  string $source_id Resource source identifier. (optional)
     * @param  array<string,mixed> $custom_fields Resource custom fields. (optional)
     * @param  string $type Resource type. (optional)
     * @param  string $format Resource format. (optional)
     * @param  bool $anonymous_access Indicates if a resource should be available by link without authorization. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resourceProcessorImportResource'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function resourceProcessorImportResourceAsync($source_file, $tenant_id = null, $name = null, $namespace = null, $source_id = null, $custom_fields = null, $type = null, $format = null, $anonymous_access = null, string $contentType = self::contentTypes['resourceProcessorImportResource'][0])
    {
        return $this->resourceProcessorImportResourceAsyncWithHttpInfo($source_file, $tenant_id, $name, $namespace, $source_id, $custom_fields, $type, $format, $anonymous_access, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation resourceProcessorImportResourceAsyncWithHttpInfo
     *
     * Imports a resource from the source file and saves it to the storage.
     *
     * @param  \SplFileObject $source_file Resource source file. (required)
     * @param  int $tenant_id Tenant ID. (optional)
     * @param  string $name Resource name. (optional)
     * @param  string $namespace Resource namespace. (optional)
     * @param  string $source_id Resource source identifier. (optional)
     * @param  array<string,mixed> $custom_fields Resource custom fields. (optional)
     * @param  string $type Resource type. (optional)
     * @param  string $format Resource format. (optional)
     * @param  bool $anonymous_access Indicates if a resource should be available by link without authorization. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resourceProcessorImportResource'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function resourceProcessorImportResourceAsyncWithHttpInfo($source_file, $tenant_id = null, $name = null, $namespace = null, $source_id = null, $custom_fields = null, $type = null, $format = null, $anonymous_access = null, string $contentType = self::contentTypes['resourceProcessorImportResource'][0])
    {
        $returnType = '\Aurigma\AssetProcessor\Model\ResourceDto';
        $request = $this->resourceProcessorImportResourceRequest($source_file, $tenant_id, $name, $namespace, $source_id, $custom_fields, $type, $format, $anonymous_access, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'resourceProcessorImportResource'
     *
     * @param  \SplFileObject $source_file Resource source file. (required)
     * @param  int $tenant_id Tenant ID. (optional)
     * @param  string $name Resource name. (optional)
     * @param  string $namespace Resource namespace. (optional)
     * @param  string $source_id Resource source identifier. (optional)
     * @param  array<string,mixed> $custom_fields Resource custom fields. (optional)
     * @param  string $type Resource type. (optional)
     * @param  string $format Resource format. (optional)
     * @param  bool $anonymous_access Indicates if a resource should be available by link without authorization. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resourceProcessorImportResource'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function resourceProcessorImportResourceRequest($source_file, $tenant_id = null, $name = null, $namespace = null, $source_id = null, $custom_fields = null, $type = null, $format = null, $anonymous_access = null, string $contentType = self::contentTypes['resourceProcessorImportResource'][0])
    {

        // verify the required parameter 'source_file' is set
        if ($source_file === null || (is_array($source_file) && count($source_file) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $source_file when calling resourceProcessorImportResource'
            );
        }










        $resourcePath = '/api/processor/v1/resources/import';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $tenant_id,
            'tenantId', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);



        // form params
        if ($name !== null) {
            $formParams['name'] = ObjectSerializer::toFormValue($name);
        }
        // form params
        if ($namespace !== null) {
            $formParams['namespace'] = ObjectSerializer::toFormValue($namespace);
        }
        // form params
        if ($source_id !== null) {
            $formParams['sourceId'] = ObjectSerializer::toFormValue($source_id);
        }
        // form params
        if ($custom_fields !== null) {
            $formParams['customFields'] = ObjectSerializer::toFormValue($custom_fields);
        }
        // form params
        if ($type !== null) {
            $formParams['type'] = ObjectSerializer::toFormValue($type);
        }
        // form params
        if ($format !== null) {
            $formParams['format'] = ObjectSerializer::toFormValue($format);
        }
        // form params
        if ($anonymous_access !== null) {
            $formParams['anonymousAccess'] = ObjectSerializer::toFormValue($anonymous_access);
        }
        // form params
        if ($source_file !== null) {
            $multipart = true;
            $formParams['sourceFile'] = [];
            $paramFiles = is_array($source_file) ? $source_file : [$source_file];
            foreach ($paramFiles as $paramFile) {
                $formParams['sourceFile'][] = \GuzzleHttp\Psr7\Utils::tryFopen(
                    ObjectSerializer::toFormValue($paramFile),
                    'rb'
                );
            }
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation resourceProcessorImportResourceFromUrl
     *
     * Imports a resource from the remote source file and saves it to the storage.
     *
     * @param  int $tenant_id Tenant ID. (optional)
     * @param  \Aurigma\AssetProcessor\Model\ImportResourceFromUrlModel $import_resource_from_url_model Parameters of the import operation. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resourceProcessorImportResourceFromUrl'] to see the possible values for this operation
     *
     * @throws \Aurigma\AssetProcessor\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Aurigma\AssetProcessor\Model\ResourceDto|\Aurigma\AssetProcessor\Model\ProblemDetails|\Aurigma\AssetProcessor\Model\ResourceImportConflictDto
     */
    public function resourceProcessorImportResourceFromUrl($tenant_id = null, $import_resource_from_url_model = null, string $contentType = self::contentTypes['resourceProcessorImportResourceFromUrl'][0])
    {
        list($response) = $this->resourceProcessorImportResourceFromUrlWithHttpInfo($tenant_id, $import_resource_from_url_model, $contentType);
        return $response;
    }

    /**
     * Operation resourceProcessorImportResourceFromUrlWithHttpInfo
     *
     * Imports a resource from the remote source file and saves it to the storage.
     *
     * @param  int $tenant_id Tenant ID. (optional)
     * @param  \Aurigma\AssetProcessor\Model\ImportResourceFromUrlModel $import_resource_from_url_model Parameters of the import operation. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resourceProcessorImportResourceFromUrl'] to see the possible values for this operation
     *
     * @throws \Aurigma\AssetProcessor\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Aurigma\AssetProcessor\Model\ResourceDto|\Aurigma\AssetProcessor\Model\ProblemDetails|\Aurigma\AssetProcessor\Model\ResourceImportConflictDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function resourceProcessorImportResourceFromUrlWithHttpInfo($tenant_id = null, $import_resource_from_url_model = null, string $contentType = self::contentTypes['resourceProcessorImportResourceFromUrl'][0])
    {
        $request = $this->resourceProcessorImportResourceFromUrlRequest($tenant_id, $import_resource_from_url_model, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 201:
                    if ('\Aurigma\AssetProcessor\Model\ResourceDto' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Aurigma\AssetProcessor\Model\ResourceDto' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Aurigma\AssetProcessor\Model\ResourceDto', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Aurigma\AssetProcessor\Model\ProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Aurigma\AssetProcessor\Model\ProblemDetails' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Aurigma\AssetProcessor\Model\ProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 409:
                    if ('\Aurigma\AssetProcessor\Model\ResourceImportConflictDto' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Aurigma\AssetProcessor\Model\ResourceImportConflictDto' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Aurigma\AssetProcessor\Model\ResourceImportConflictDto', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Aurigma\AssetProcessor\Model\ResourceDto';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Aurigma\AssetProcessor\Model\ResourceDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Aurigma\AssetProcessor\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Aurigma\AssetProcessor\Model\ResourceImportConflictDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation resourceProcessorImportResourceFromUrlAsync
     *
     * Imports a resource from the remote source file and saves it to the storage.
     *
     * @param  int $tenant_id Tenant ID. (optional)
     * @param  \Aurigma\AssetProcessor\Model\ImportResourceFromUrlModel $import_resource_from_url_model Parameters of the import operation. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resourceProcessorImportResourceFromUrl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function resourceProcessorImportResourceFromUrlAsync($tenant_id = null, $import_resource_from_url_model = null, string $contentType = self::contentTypes['resourceProcessorImportResourceFromUrl'][0])
    {
        return $this->resourceProcessorImportResourceFromUrlAsyncWithHttpInfo($tenant_id, $import_resource_from_url_model, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation resourceProcessorImportResourceFromUrlAsyncWithHttpInfo
     *
     * Imports a resource from the remote source file and saves it to the storage.
     *
     * @param  int $tenant_id Tenant ID. (optional)
     * @param  \Aurigma\AssetProcessor\Model\ImportResourceFromUrlModel $import_resource_from_url_model Parameters of the import operation. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resourceProcessorImportResourceFromUrl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function resourceProcessorImportResourceFromUrlAsyncWithHttpInfo($tenant_id = null, $import_resource_from_url_model = null, string $contentType = self::contentTypes['resourceProcessorImportResourceFromUrl'][0])
    {
        $returnType = '\Aurigma\AssetProcessor\Model\ResourceDto';
        $request = $this->resourceProcessorImportResourceFromUrlRequest($tenant_id, $import_resource_from_url_model, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'resourceProcessorImportResourceFromUrl'
     *
     * @param  int $tenant_id Tenant ID. (optional)
     * @param  \Aurigma\AssetProcessor\Model\ImportResourceFromUrlModel $import_resource_from_url_model Parameters of the import operation. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resourceProcessorImportResourceFromUrl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function resourceProcessorImportResourceFromUrlRequest($tenant_id = null, $import_resource_from_url_model = null, string $contentType = self::contentTypes['resourceProcessorImportResourceFromUrl'][0])
    {




        $resourcePath = '/api/processor/v1/resources/import/from-url';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $tenant_id,
            'tenantId', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($import_resource_from_url_model)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($import_resource_from_url_model));
            } else {
                $httpBody = $import_resource_from_url_model;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation resourceProcessorUpdate
     *
     * Updates the resource file and metadata in the storage.
     *
     * @param  string $id Resource entity ID. (required)
     * @param  int $tenant_id Tenant ID. (optional)
     * @param  string $name Resource name. (optional)
     * @param  string $namespace Resource namespace. (optional)
     * @param  string $source_id Resource source identifier. (optional)
     * @param  array<string,mixed> $custom_fields Resource custom fields. (optional)
     * @param  string $type Resource type. (optional)
     * @param  string $format Resource format. (optional)
     * @param  bool $anonymous_access Indicates if a resource should be available by link without authorization. (optional)
     * @param  \SplFileObject $file Resource source file. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resourceProcessorUpdate'] to see the possible values for this operation
     *
     * @throws \Aurigma\AssetProcessor\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Aurigma\AssetProcessor\Model\ResourceDto|\Aurigma\AssetProcessor\Model\ProblemDetails|\Aurigma\AssetProcessor\Model\ResourceUpdateConflictDto
     */
    public function resourceProcessorUpdate($id, $tenant_id = null, $name = null, $namespace = null, $source_id = null, $custom_fields = null, $type = null, $format = null, $anonymous_access = null, $file = null, string $contentType = self::contentTypes['resourceProcessorUpdate'][0])
    {
        list($response) = $this->resourceProcessorUpdateWithHttpInfo($id, $tenant_id, $name, $namespace, $source_id, $custom_fields, $type, $format, $anonymous_access, $file, $contentType);
        return $response;
    }

    /**
     * Operation resourceProcessorUpdateWithHttpInfo
     *
     * Updates the resource file and metadata in the storage.
     *
     * @param  string $id Resource entity ID. (required)
     * @param  int $tenant_id Tenant ID. (optional)
     * @param  string $name Resource name. (optional)
     * @param  string $namespace Resource namespace. (optional)
     * @param  string $source_id Resource source identifier. (optional)
     * @param  array<string,mixed> $custom_fields Resource custom fields. (optional)
     * @param  string $type Resource type. (optional)
     * @param  string $format Resource format. (optional)
     * @param  bool $anonymous_access Indicates if a resource should be available by link without authorization. (optional)
     * @param  \SplFileObject $file Resource source file. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resourceProcessorUpdate'] to see the possible values for this operation
     *
     * @throws \Aurigma\AssetProcessor\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Aurigma\AssetProcessor\Model\ResourceDto|\Aurigma\AssetProcessor\Model\ProblemDetails|\Aurigma\AssetProcessor\Model\ResourceUpdateConflictDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function resourceProcessorUpdateWithHttpInfo($id, $tenant_id = null, $name = null, $namespace = null, $source_id = null, $custom_fields = null, $type = null, $format = null, $anonymous_access = null, $file = null, string $contentType = self::contentTypes['resourceProcessorUpdate'][0])
    {
        $request = $this->resourceProcessorUpdateRequest($id, $tenant_id, $name, $namespace, $source_id, $custom_fields, $type, $format, $anonymous_access, $file, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Aurigma\AssetProcessor\Model\ResourceDto' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Aurigma\AssetProcessor\Model\ResourceDto' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Aurigma\AssetProcessor\Model\ResourceDto', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\Aurigma\AssetProcessor\Model\ProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Aurigma\AssetProcessor\Model\ProblemDetails' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Aurigma\AssetProcessor\Model\ProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 409:
                    if ('\Aurigma\AssetProcessor\Model\ResourceUpdateConflictDto' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Aurigma\AssetProcessor\Model\ResourceUpdateConflictDto' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Aurigma\AssetProcessor\Model\ResourceUpdateConflictDto', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Aurigma\AssetProcessor\Model\ResourceDto';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Aurigma\AssetProcessor\Model\ResourceDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Aurigma\AssetProcessor\Model\ProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Aurigma\AssetProcessor\Model\ResourceUpdateConflictDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation resourceProcessorUpdateAsync
     *
     * Updates the resource file and metadata in the storage.
     *
     * @param  string $id Resource entity ID. (required)
     * @param  int $tenant_id Tenant ID. (optional)
     * @param  string $name Resource name. (optional)
     * @param  string $namespace Resource namespace. (optional)
     * @param  string $source_id Resource source identifier. (optional)
     * @param  array<string,mixed> $custom_fields Resource custom fields. (optional)
     * @param  string $type Resource type. (optional)
     * @param  string $format Resource format. (optional)
     * @param  bool $anonymous_access Indicates if a resource should be available by link without authorization. (optional)
     * @param  \SplFileObject $file Resource source file. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resourceProcessorUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function resourceProcessorUpdateAsync($id, $tenant_id = null, $name = null, $namespace = null, $source_id = null, $custom_fields = null, $type = null, $format = null, $anonymous_access = null, $file = null, string $contentType = self::contentTypes['resourceProcessorUpdate'][0])
    {
        return $this->resourceProcessorUpdateAsyncWithHttpInfo($id, $tenant_id, $name, $namespace, $source_id, $custom_fields, $type, $format, $anonymous_access, $file, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation resourceProcessorUpdateAsyncWithHttpInfo
     *
     * Updates the resource file and metadata in the storage.
     *
     * @param  string $id Resource entity ID. (required)
     * @param  int $tenant_id Tenant ID. (optional)
     * @param  string $name Resource name. (optional)
     * @param  string $namespace Resource namespace. (optional)
     * @param  string $source_id Resource source identifier. (optional)
     * @param  array<string,mixed> $custom_fields Resource custom fields. (optional)
     * @param  string $type Resource type. (optional)
     * @param  string $format Resource format. (optional)
     * @param  bool $anonymous_access Indicates if a resource should be available by link without authorization. (optional)
     * @param  \SplFileObject $file Resource source file. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resourceProcessorUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function resourceProcessorUpdateAsyncWithHttpInfo($id, $tenant_id = null, $name = null, $namespace = null, $source_id = null, $custom_fields = null, $type = null, $format = null, $anonymous_access = null, $file = null, string $contentType = self::contentTypes['resourceProcessorUpdate'][0])
    {
        $returnType = '\Aurigma\AssetProcessor\Model\ResourceDto';
        $request = $this->resourceProcessorUpdateRequest($id, $tenant_id, $name, $namespace, $source_id, $custom_fields, $type, $format, $anonymous_access, $file, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'resourceProcessorUpdate'
     *
     * @param  string $id Resource entity ID. (required)
     * @param  int $tenant_id Tenant ID. (optional)
     * @param  string $name Resource name. (optional)
     * @param  string $namespace Resource namespace. (optional)
     * @param  string $source_id Resource source identifier. (optional)
     * @param  array<string,mixed> $custom_fields Resource custom fields. (optional)
     * @param  string $type Resource type. (optional)
     * @param  string $format Resource format. (optional)
     * @param  bool $anonymous_access Indicates if a resource should be available by link without authorization. (optional)
     * @param  \SplFileObject $file Resource source file. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resourceProcessorUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function resourceProcessorUpdateRequest($id, $tenant_id = null, $name = null, $namespace = null, $source_id = null, $custom_fields = null, $type = null, $format = null, $anonymous_access = null, $file = null, string $contentType = self::contentTypes['resourceProcessorUpdate'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling resourceProcessorUpdate'
            );
        }











        $resourcePath = '/api/processor/v1/resources/{id}/update';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $tenant_id,
            'tenantId', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // form params
        if ($name !== null) {
            $formParams['name'] = ObjectSerializer::toFormValue($name);
        }
        // form params
        if ($namespace !== null) {
            $formParams['namespace'] = ObjectSerializer::toFormValue($namespace);
        }
        // form params
        if ($source_id !== null) {
            $formParams['sourceId'] = ObjectSerializer::toFormValue($source_id);
        }
        // form params
        if ($custom_fields !== null) {
            $formParams['customFields'] = ObjectSerializer::toFormValue($custom_fields);
        }
        // form params
        if ($type !== null) {
            $formParams['type'] = ObjectSerializer::toFormValue($type);
        }
        // form params
        if ($format !== null) {
            $formParams['format'] = ObjectSerializer::toFormValue($format);
        }
        // form params
        if ($anonymous_access !== null) {
            $formParams['anonymousAccess'] = ObjectSerializer::toFormValue($anonymous_access);
        }
        // form params
        if ($file !== null) {
            $multipart = true;
            $formParams['file'] = [];
            $paramFiles = is_array($file) ? $file : [$file];
            foreach ($paramFiles as $paramFile) {
                $formParams['file'][] = \GuzzleHttp\Psr7\Utils::tryFopen(
                    ObjectSerializer::toFormValue($paramFile),
                    'rb'
                );
            }
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
