<?php
/**
 * DesignImportType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Asset Processor API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\AssetProcessor\Model;
use \Aurigma\AssetProcessor\ObjectSerializer;

/**
 * DesignImportType Class Doc Comment
 *
 * @category Class
 * @description Design import type.
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DesignImportType
{
    /**
     * Possible values of this enum
     */
    public const STATE = 'State';

    public const SIMPLE_IMAGE = 'SimpleImage';

    public const VECTOR_IMAGE = 'VectorImage';

    public const PSD = 'PSD';

    public const IDML = 'IDML';

    public const PDF = 'PDF';

    public const EPS = 'EPS';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::STATE,
            self::SIMPLE_IMAGE,
            self::VECTOR_IMAGE,
            self::PSD,
            self::IDML,
            self::PDF,
            self::EPS
        ];
    }
}


